// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjO_5gu5EBgPJAdXvE4QZiGtGfA2Ubbnk',
    appId: '1:460569370123:web:7fb6209322a510fa6df10e',
    messagingSenderId: '460569370123',
    projectId: 'faisal-store-1c7fe',
    authDomain: 'faisal-store-1c7fe.firebaseapp.com',
    storageBucket: 'faisal-store-1c7fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwenjG_tGsiSkjr4qSuXFqmdA6tCF3I4',
    appId: '1:460569370123:android:368669873d3145526df10e',
    messagingSenderId: '460569370123',
    projectId: 'faisal-store-1c7fe',
    storageBucket: 'faisal-store-1c7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kvqWxzJLK549RBklWdiwfowx3ZU5q9g',
    appId: '1:460569370123:ios:6a41911e570774dd6df10e',
    messagingSenderId: '460569370123',
    projectId: 'faisal-store-1c7fe',
    storageBucket: 'faisal-store-1c7fe.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kvqWxzJLK549RBklWdiwfowx3ZU5q9g',
    appId: '1:460569370123:ios:de23b5e6551c1e446df10e',
    messagingSenderId: '460569370123',
    projectId: 'faisal-store-1c7fe',
    storageBucket: 'faisal-store-1c7fe.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
